chore: switch from vite-plugin-md to unplugin-vue-markdown
vite-plugin-md@0.13 introduced a major change, and the old way has been forked
to unplugin-vue-markdown. See https://github.com/antfu/vite-plugin-md

lang="ts" had to be removed in order to avoid
Error: [@vue/compiler-sfc] <script> and <script setup> must have the same language type.